export enum PostTypes {
  // FETCH POSTS
  FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST',
  FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE',

  // FETCH A PARTICULAR POST
  FETCH_POST_DETAIL_REQUEST = 'FETCH_POST_DETAIL_REQUEST',
  FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS',
  FETCH_POST_DETAIL_FAILURE = 'FETCH_POST_DETAIL_FAILURE',
}
